version: "3.8"

services:
  db:
    image: mariadb:10.6.9
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    ports:
      - "8080:8080"

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    container_name: socket_server
    networks:
      - backend
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  db_data:

networks:
  backend:
    driver: bridge