package scg.buzzsnap.model;
// Generated 27 dic 2024 20:43:20 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "buzzsnap", uniqueConstraints = @UniqueConstraint(columnNames = "invite_code"))
public class Groups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Users creator;
	private String name;
	private String image_url;
	private String description;
	private String invite_code;
	private Date created_at;

	public Groups() {
	}

	public Groups(Users createdBy, String name, String inviteCode, Date createdAt) {
		this.creator = createdBy;
		this.name = name;
		this.invite_code = inviteCode;
		this.created_at = createdAt;
	}

	public Groups(Users createdBy, String name, String imageUrl, String description, String inviteCode, Date createdAt) {
		this.name = name;
		this.image_url = imageUrl;
		this.description = description;
		this.creator = createdBy;
		this.invite_code = inviteCode;
		this.created_at = createdAt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by", nullable = false)
	public Users getCreator() {
		return this.creator;
	}

	public void setCreator(Users createdBy) {
		this.creator = createdBy;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.image_url;
	}

	public void setImageUrl(String imageUrl) {
		this.image_url = imageUrl;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "invite_code", unique = true, nullable = false, length = 8)
	public String getInviteCode() {
		return this.invite_code;
	}

	public void setInviteCode(String inviteCode) {
		this.invite_code = inviteCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.created_at;
	}

	public void setCreatedAt(Date createdAt) {
		this.created_at = createdAt;
	}

}
