package scg.buzzsnap.model;

import java.time.LocalDateTime;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Chats generated by hbm2java
 */
@Entity
@Table(name = "chats", catalog = "buzzsnap")
public class Chats implements java.io.Serializable{
	

	private static final long serialVersionUID = 1L;
    private Integer id; 
    private Users user1;  
    private Users user2;  
    private Date created_at; 
    private String users_order; 
    
    public Chats() {
	}

	public Chats(Users user1Id, Users user2Id, Date createdAt, String usersOrder) {
		this.user1 = user1Id;
		this.user2 = user2Id;
		this.created_at = createdAt;
		this.users_order = usersOrder;
	}


	 @Id
	 @GeneratedValue(strategy = GenerationType.IDENTITY)
	 @Column(name = "id", unique = true, nullable = false)
	 public Integer getId() {
		 return this.id;
	 }

	 public void setId(Integer id) {
	     this.id = id;
	 }

	 @ManyToOne(fetch = FetchType.EAGER)
	 @JoinColumn(name = "user1_id", nullable = false)
	 public Users getUser1() {
	     return this.user1;
	 }

	 public void setUser1(Users user1Id) {
	     this.user1 = user1Id;
	 }

	 @ManyToOne(fetch = FetchType.EAGER)
	 @JoinColumn(name = "user2_id", nullable = false)
	 public Users getUser2() {
	     return this.user2;
	 }

	 public void setUser2(Users user2Id) {
	     this.user2 = user2Id;
	 }

	 @Column(name = "users_order", nullable = false, length = 50)
	 public String getUsersOrder() {
	     return this.users_order;
	 }

	 public void setUsersOrder(String usersOrder) {
	     this.users_order = usersOrder;
	 }

	 @Temporal(TemporalType.TIMESTAMP)
	 @Column(name = "created_at", nullable = false, length = 19)
	 public Date getCreatedAt() {
	     return this.created_at;
	 }

	 public void setCreatedAt(Date createdAt) {
	     this.created_at = createdAt;
	}
}

