package scg.buzzsnap.model;
// Generated 27 dic 2024 20:43:20 by Hibernate Tools 3.6.2.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Friends generated by hbm2java
 */
@Entity
@Table(name = "friends", catalog = "buzzsnap")
public class Friends implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Users user;
	private Users friend;
	private String status;
	private Date created_at;
    private String users_order; 

	public Friends() {
	}

	public Friends(Users userId, Users friendId, String status, Date createdAt, String usersOrder) {
		this.user = userId;
		this.friend = friendId;
		this.status = status;
		this.created_at = createdAt;
		this.users_order = usersOrder;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUser() {
		return this.user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "friend_id", nullable = false)
	public Users getFriend() {
		return this.friend;
	}

	public void setFriend(Users friendId) {
		this.friend = friendId;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@Column(name = "users_order", nullable = false, length = 50)
	 public String getUsersOrder() {
	     return this.users_order;
	 }

	 public void setUsersOrder(String usersOrder) {
	 }

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.created_at;
	}

	public void setCreatedAt(Date createdAt) {
		this.created_at = createdAt;
	}
	

}
