package scg.buzzsnap.model;
//Generated 27 dic 2024 20:43:20 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

/**
 * GroupMembers generated by hbm2java
 */
@Entity
@Table(name = "group_members", catalog = "buzzsnap")
public class GroupMembers implements java.io.Serializable {
	/**
	 * 
	 */
    private static final long serialVersionUID = 1L;

    private Integer id;
    private Groups group;
    private Users user;
    private String role;
    private Date joined_at;

    public GroupMembers() {
    }

    public GroupMembers(Groups group, Users user, String role, Date joinedAt) {
        this.group = group;
        this.user = user;
        this.role = role;
        this.joined_at = joinedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "group_id", nullable = false)
    public Groups getGroup() {
        return this.group;
    }

    public void setGroup(Groups group) {
        this.group = group;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    public Users getUser() {
        return this.user;
    }

    public void setUser(Users user) {
        this.user = user;
    }

    @Column(name = "role", nullable = false, length = 10)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "joined_at", nullable = false)
    public Date getJoinedAt() {
        return this.joined_at;
    }

    public void setJoinedAt(Date joinedAt) {
        this.joined_at = joinedAt;
    }
}
