package scg.buzzsnap.model;
// Generated 27 dic 2024 20:43:20 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name = "messages", catalog = "buzzsnap")
public class Messages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Users sender;
	private Chats chat;
	private Groups group;
	private String message_type;
	private String content;
	private Date created_at;

	public Messages() {
	}

	public Messages(Users senderId, Chats chatId, String messageType, String content,
			Date createdAt) {
		this.sender = senderId;
		this.chat = chatId;
		this.message_type = messageType;
		this.content = content;
		this.created_at = createdAt;
	}
	
	public Messages(Users senderId, Groups groupId, String messageType, String content,
			Date createdAt) {
		this.sender = senderId;
		this.group = groupId;
		this.message_type = messageType;
		this.content = content;
		this.created_at = createdAt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sender_id", nullable = false)
	public Users getSender() {
		return this.sender;
	}

	public void setSender(Users senderId) {
		this.sender = senderId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "chat_id")
	public Chats getChat() {
		return this.chat;
	}

	public void setChat(Chats chatId) {
		this.chat = chatId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "group_id")
	public Groups getGroup() {
		return this.group;
	}

	public void setGroup(Groups groupId) {
		this.group = groupId;
	}

	@Column(name = "message_type", nullable = false, length = 5)
	public String getMessageType() {
		return this.message_type;
	}

	public void setMessageType(String messageType) {
		this.message_type = messageType;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.created_at;
	}

	public void setCreatedAt(Date createdAt) {
		this.created_at = createdAt;
	}
	

}
