package scg.buzzsnap.model;
// Generated 27 dic 2024 20:43:20 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "buzzsnap", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String display_name;
	private String email;
	private String password;
	private String avatar_url;
	private String description;
	private String theme;
	private Date last_login;
	private Date created_at;
	private Boolean closed;

	public Users() {
	}

	public Users(String name, String email, String displayName, String password, Date lastLogin, Date createdAt) {
	    this.name = name;
	    this.email = email;
	    this.display_name = (displayName != null && !displayName.isEmpty()) ? displayName : name.toLowerCase();
	    this.password = password;
	    this.last_login = lastLogin;
	    this.created_at = createdAt;
	}

	public Users(String name, String email, String displayName, String password, String avatarUrl, String description, String theme,
			Date lastLogin, Date createdAt, Boolean closed) {
		this.name = name;
		this.email = email;
		this.display_name = displayName;
		this.password = password;
		this.avatar_url = avatarUrl;
		this.description = description;
		this.theme = theme;
		this.last_login = lastLogin;
		this.created_at = createdAt;
		this.closed = closed;
		
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique=true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "display_name", nullable = false)
	public String getDisplayName() {
		return this.display_name;
	}

	public void setDisplayName(String displayName) {
		this.display_name = displayName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "avatar_url")
	public String getAvatarUrl() {
		return this.avatar_url;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatar_url = avatarUrl;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "theme", length = 50)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login", nullable = true, length = 19)
	public Date getLastLogin() {
		return this.last_login;
	}

	public void setLastLogin(Date lastLogin) {
		this.last_login = lastLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.created_at;
	}

	public void setCreatedAt(Date createdAt) {
		this.created_at = createdAt;
	}
	
	@Column(name = "closed")
	public Boolean getClosed() {
	    return this.closed;
	}

	public void setClosed(Boolean closed) {
	    this.closed = closed;
	}

}
